CREATE TABLE [dbo].[Profile]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[LookupId] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[Username] NVARCHAR(100) NOT NULL,
	[PasswordHash] NVARCHAR(64) NOT NULL,
	[Salt] NVARCHAR(64) NOT NULL,
	[Role] NVARCHAR(50) NOT NULL,
	[CreatedOn] DATETIMEOFFSET
);
GO
