CREATE TABLE [dbo].[Profile]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[LookupId] UNIQUEIDENTIFIER NOT NULL,
	[Username] NVARCHAR(100) NOT NULL,
	[PasswordHash] NVARCHAR(64) NOT NULL,
	[Salt] NVARCHAR(16) NOT NULL,
	[Role] NVARCHAR(50) NOT NULL,
	[CreatedOn] DATETIMEOFFSET
);
GO
CREATE INDEX [IX_LookupId]
ON [dbo].[Profile] ([LookupId])
GO
